### ISSUE TITLE
For Pine64 Ubuntu docker run fails

### ISSUE THREAD

**Issue by fnpc** [umiddelb/z2d#12]
Error: oci runtime error: could not synchronise with container process: could not create session key: function not implemented

root@p64:/# ./usr/share/docker.io/contrib/check-config.sh
info: reading kernel config from /proc/config.gz ...
Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

root@p64:/# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.102
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 978.4 MiB
Name: p64
ID: VVDN:3AG3:UGJD:3PDX:7PML:72KL:PYVY:6FKL:HXY3:E72D:IZEJ:ZCUG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

**Comment by umiddelb** [comment]
Hi,

you may provide some more context information about this case, e.g. the Linux Distribution you are using and the output of `docker version`.

I guess that you have build Docker 1.12 from source. In this case you'll get not a single binary but a whole bunch which have to be moved to `/usr/bin`, this layout is working for me:
```
ubuntu@c2:~$ ls -l /usr/bin/docker*
lrwxrwxrwx 1 root root       17 Aug 30 08:16 /usr/bin/docker -> docker-1.12.0-dev
-rwxr-xr-x 1 root root 33188272 Apr 21 02:17 /usr/bin/docker-1.10.3
-rwxr-xr-x 1 root root 34140016 Jul  8 01:06 /usr/bin/docker-1.11.2
-rwxr-xr-x 1 root root 14985680 Jul 10 22:17 /usr/bin/docker-1.12.0-dev
-rwxr-xr-x 1 root root 10846824 Jul 10 22:18 /usr/bin/docker-containerd
-rwxr-xr-x 1 root root 10147856 Jul 10 22:18 /usr/bin/docker-containerd-ctr
-rwxr-xr-x 1 root root  3591288 Jul 10 22:18 /usr/bin/docker-containerd-shim
lrwxrwxrwx 1 root root       18 Aug 30 00:36 /usr/bin/dockerd -> dockerd-1.12.0-dev
-rwxr-xr-x 1 root root 44245464 Jul 10 22:19 /usr/bin/dockerd-1.12.0-dev
lrwxrwxrwx 1 root root       23 Aug 30 00:36 /usr/bin/docker-proxy -> docker-proxy-1.12.0-dev
-rwxr-xr-x 1 root root  2989578 Jul 10 22:19 /usr/bin/docker-proxy-1.12.0-dev
-rwxr-xr-x 1 root root  8477664 Jul 10 22:19 /usr/bin/docker-runc
```
