### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by dz00te** [umiddelb/z2d#14]
i'm trying to install centos7 on pine64 (following kurtstam instruction), but i have an error on 
centos-00.sh -> ubuntu-core-00.sh
on last line

`curl -sSL https://github.com/umiddelb/u-571/blob/master/board/pine64+/uboot.env.xz?raw=true | unxz | sudo dd of=./rootfs/bootenv/uboot.env
`
the file seems no more available, i'm missing something?

**Comment by ioft** [comment]
Hi @dz00te ,

thank you very much for pointing me to this issue (and sorry for not responding in a timely manner).

In the last couple of weeks, if moved from the BSP to the mainline u-boot and mainline kernel on the Pine64, but I forgot the reflect this changes here as well. I'll ping you when I'm done with refactoring. 

Cheers
Uli

**Comment by ioft** [comment]
You may try it once again via z2d.

**Comment by dz00te** [comment]
thank you i've just retested, and it's working
i've some problem with hdmi and usb but i'll check later
thank you!

**Comment by ioft** [comment]
> thank you i've just retested, and it's working

Cool

>i've some problem with hdmi and usb but i'll check later thank you!

You're welcome. HDMI isn't supposed to work. The lower USB receptacle should work.
