### ISSUE TITLE
error in debian setup

### ISSUE THREAD

**Issue by FAUSheppy** [umiddelb/z2d#15]
./uboot-env: 1: ./uboot-env: Syntax error word unexpected (expecting ")" ) 

Happens on Debian Stretch when trying to execute ./debian-00.sh, not sure what this message is trying to tell me.

**Comment by umiddelb** [comment]
You need to run the z2d scripts on the target platform, i.e. not on X86.

Which board do you want to set up with z2d?

**Comment by FireHelmet** [comment]
Hello @umiddelb 

it's an old topic, but I have the same issue. Maybe I don't understand well how to execute the scripts...

I try to run your scripts from an ubuntu 16.04 LTS in live cd to prepare my sdcard...

In addition, I'm trying to install Alpine OS on Odroid C2.

Could you help me ?

Thanks !!

**Comment by umiddelb** [comment]
Hello @FireHelmet 

the z2d scripts need to be run on the same platform as the target platform. If you want to deploy it on a Odroid C2, the target platform needs to be Aarch64. If the Odroid is your only Aarch64 device, you need to run the scripts on the C2 itself. If you have bought an eMMC chip with your C2, you can tell z2d to take the SD card as the target (and vice versa). If not, you need an external SD card reader connected to one of the USB ports. 

For bootstrapping, choose one the [Armbian images made for the C2](https://dl.armbian.com/odroidc2/).  Please use [Etcher](https://etcher.io/) for burning the image to the SD card.
