### ISSUE TITLE
Odroid-C2 does not boot.

### ISSUE THREAD

**Issue by thieso2** [umiddelb/z2d#20]
Hi, 

I create sd-cards using your scripts with minimal adjustments (dev=sda in alpine-00.sh). With some fiddeling I managed to get the scripts to work with no errors an the sd-cards gets written, ./uboot-env runs with no errors. Problem is that the generated sd-card does not boot. My odroid-c2 does not start the blue led at all. no hdmi-out, nothing.

thanx, thies

**Comment by umiddelb** [comment]
Hi Thies,
HK silently changed their download URL to fetch the firmware, this is fixed [here](https://github.com/umiddelb/z2d/commit/841b43c02d12ee523b5336563b3c9f99a9a17314).
Alpine 3.5 has also received some (strange) changes, the uboot-tools package can be considered broken in 3.5.
The network interfaces don't come up automatically at boot any more, you need to log-on via serial console and run `ifup -a`
I've tried to switch to alpine 3.6, but my login shell SEGFAULTs after a couple of seconds.  
I must admit that I don't use alpine frequently, so any improvement is welcome.

Cheers Uli

**Comment by thieso2** [comment]
(back from vacation)

Thank you so much!
