### ISSUE TITLE
CentOS for Pine64 - blank screen

### ISSUE THREAD

**Issue by tcreek** [umiddelb/z2d#21]
Following the guide at:

https://github.com/umiddelb/z2d/tree/master/pine64

I get no error for installing the image to SD card, but on boot I only a black screen.

**Comment by umiddelb** [comment]
Do you have access to the Pine's serial console? Usually I don't pay much attention to HDMI output, it might be disabled in this kernel version.

**Comment by tcreek** [comment]
Yes, I have access and see it has booted. It seems there is no output to the screen via HDMI

**Comment by tcreek** [comment]
Just to let you know, I ended up having to change the root password via chroot since none of the listed credentials are correct. 

In addition, the image is very buggy on a Pine64. I will just wait until a dedicated image is created for it.

**Comment by umiddelb** [comment]
> Just to let you know, I ended up having to change the root password via chroot since none of the listed credentials are correct.

To which list do you refer to? You will be asked for new passwords for the [root user](https://github.com/umiddelb/z2d/blob/master/pine64/centos-02.sh#L16) and the [centos user](https://github.com/umiddelb/z2d/blob/master/pine64/centos-02.sh#L19) during setup.

> In addition, the image is very buggy on a Pine64.

Please elaborate.

> I will just wait until a dedicated image is created for it.

This is very unlikely to happen, since the Pine64 doesn't meet SBSA requirements (like many other boards).

**Comment by tcreek** [comment]
On your project page you have nothing listed. On the Pine64 it is listed, but incorrect, and on the the original project of the creator, it is listed, but also incorrect.

Buggy, as it seems to be very sluggish, and many applications do not function correctly. For example, wget executes, but never obtains the target file, it just hangs.

**Comment by umiddelb** [comment]
> On your project page you have nothing listed. On the Pine64 it is listed, but incorrect, and on the the original project of the creator, it is listed, but also incorrect. I also tried that root/centos and it fails.

Could you provide links, please?

> Buggy, as it seems to be very sluggish, and many applications do not function correctly. For example, wget executes, but never obtains the target file, it just hangs.

Some Pine64 boards have been shipped with a broken Ethernet adapter. There are some tweaks/workarounds for the BSP kernel but they cannot be applied to the mainline kernel. 
You may try to use a USB-Ethernet adapter on the lower USB receptacle instead.

**Comment by tcreek** [comment]
Here is the only link I have found which supplies any sort of credentials (and incorrect)

https://forum.pine64.org/showthread.php?tid=1691&highlight=CentOS


And in my case there is nothing wrong the the Ethernet port. I have tried other images with better performance, and wget functions fine.

**Comment by umiddelb** [comment]
The credentials mentioned there relate to a different image.

**Comment by tcreek** [comment]
but I was using THIS image which does not invalidate my other bug reporting

**Comment by umiddelb** [comment]
to be honest, z2d (this github repo) does not create nor publish any image. These scripts help you to install an operating system on a local device. If you refer to an _image_, this is probably the wrong place to raise a complaint. 
To clarify this issue, you may provide the image's download url.
