### ISSUE TITLE
uboot-env

### ISSUE THREAD

**Issue by moonwolf-github** [umiddelb/z2d#28]
in centos-00.sh
`uboot-env: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=b0c83fed2bb49ada776be1c6817ab05be6f112f6, stripped`

Should i run this scipt on ARM device? But i'm peparing one, how can i do it?

**Comment by umiddelb** [comment]
It's meant to be that way, i.e. you need to have linux up and running on your arm board before you can start. If you don't know how to get there, please have a look at [Armbian](https://www.armbian.com/download/).

**Comment by moonwolf-github** [comment]
OK, i understand. But don't you think it would be much more flexible if one could prepare image on regular PC?
