### ISSUE TITLE
Pine64 instructions have bad URL

### ISSUE THREAD

**Issue by khenriks** [umiddelb/z2d#8]
For the Pine64 install procedure instructions, step 6 gives a URL to download from, but that no longer seems to exist. Has it changed to something else?

I also tried following the instructions to create an SD card to boot from, but it seems to hang during boot. Maybe the step 6 I had to skip was necessary to make it work?

Thanks!

**Comment by umiddelb** [comment]
Good morning! Thank you for pointing out this issue. I've updated the information and the link to the kernel image. You can find the latest kernel images [here](https://www.dropbox.com/sh/l751jmswzr2v6o2/AADFOOTAojHvyUFxSxKSbCrya?dl=0) as well.

> I also tried following the instructions to create an SD card to boot from, but it seems to hang during boot. Maybe the step 6 I had to skip was necessary to make it work?

At this time you still need to manually update the u-boot environment at the u-boot command line since I haven't succeeded to gain userland access. Do you have a serial connection to your pine?

**Comment by khenriks** [comment]
I don't currently have a serial connection, although I could hook one up. I wanted something that would eventually let me do this in a headless configuration without needing to run anything manually to make it start. Is this possible? Do any of the Pine64 images work like this?

**Comment by umiddelb** [comment]
> Do any of the Pine64 images work like this?

Every image should boot up without manual intervention. Only if you build your own environment from scratch for the pine64 with the help of the z2d scripts you need to tweak it at this time (this is supposed to change once mainline u-boot support will be available for the pine64).

If you follow the steps mentioned [here](https://github.com/umiddelb/z2d/tree/master/pine64#install-procedure) you pine will boot up without further modifications afterwards.

If you still encounter some problems you may try [longsleep's image](http://forum.pine64.org/showthread.php?tid=376).

**Comment by khenriks** [comment]
I tried to follow the instructions you mentioned exactly, without building things myself. I used the Debian jessie boot image. Maybe I did something wrong, I can try again and see if it will work.

I was able to get it to work by using lenny's image from the [Pine64 forums](http://forum.pine64.org/showthread.php?tid=497).

**Comment by cbbrowne** [comment]
Ah, thank you for pointers to "without further modifications" notes; I have been able to happily boot up a _first_ time, but it then essentially "Black Screen of Deaths" thereafter.  Seems like I need to tweak the boot environment a very wee bit more.

I had no trouble with the initial boot, using longsleep's image, and the debian root image from here; it booted fine.  After modifying things a bit (/etc/resolv.conf, adding users), it would head back to failing to boot ("Black screen").  Hopefully there's some tweaking to get it to play better.

**Comment by umiddelb** [comment]
Do you have the serial console connected? Every 3.3 V USB-UART connector (or device with 3.3 voltage level UART like the ODROID-C1 and -C2) should work.
